export default [
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "黄宸",
    "yhdm": 1532882960,
    "yhmc": "1123",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算配置03",
    "yhdm": 1532882962,
    "yhmc": "zjtzyspz03",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江预算测试01",
    "yhdm": 1532882963,
    "yhmc": "zjyscs01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "郑章生测试",
    "yhdm": 1532882964,
    "yhmc": "zzs",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算用户03",
    "yhdm": 1532882966,
    "yhmc": "zjtzys03",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算用户04",
    "yhdm": 1532882967,
    "yhmc": "zjtzys04",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "夏晓春",
    "yhdm": 1532882969,
    "yhmc": "p31171694",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江数据地图测试1",
    "yhdm": 1532882970,
    "yhmc": "zjsjdttest1",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江数据地图测试2",
    "yhdm": 1532882971,
    "yhmc": "zjsjdttest2",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "mrmp01",
    "yhdm": -460803167,
    "yhmc": "mrmp01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "mrmp03",
    "yhdm": 1532882975,
    "yhmc": "mrmp03",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "mrmp04",
    "yhdm": 1532882976,
    "yhmc": "mrmp04",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "mrmp05",
    "yhdm": 1532882977,
    "yhmc": "mrmp05",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "hy",
    "yhdm": 1532882979,
    "yhmc": "hy",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "mrmp02",
    "yhdm": 1,
    "yhmc": "mrmp02",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置01",
    "yhdm": 1532879192,
    "yhmc": "zjpz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置02",
    "yhdm": 1532879193,
    "yhmc": "zjpz02",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置03",
    "yhdm": 1532879194,
    "yhmc": "zjpz03",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置04",
    "yhdm": 1532879195,
    "yhmc": "zjpz04",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置05",
    "yhdm": 1532879196,
    "yhmc": "zjpz05",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置06",
    "yhdm": 1532879197,
    "yhmc": "zjpz06",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置07",
    "yhdm": 1532879198,
    "yhmc": "zjpz07",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置08",
    "yhdm": 1532879199,
    "yhmc": "zjpz08",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置09",
    "yhdm": 1532879200,
    "yhmc": "zjpz09",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江配置10",
    "yhdm": 1532879201,
    "yhmc": "zjpz10",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务01",
    "yhdm": 1532879202,
    "yhmc": "zjyw01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务02",
    "yhdm": 1532879203,
    "yhmc": "zjyw02",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务03",
    "yhdm": 1532879204,
    "yhmc": "zjyw03",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务04",
    "yhdm": 1532879205,
    "yhmc": "zjyw04",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务05",
    "yhdm": 1532879206,
    "yhmc": "zjyw05",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "报账业务001",
    "yhdm": 1532879207,
    "yhmc": "bz001",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务07",
    "yhdm": 1532879208,
    "yhmc": "zjyw07",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "杨水英",
    "yhdm": 1532879209,
    "yhmc": "zjyw08",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务09",
    "yhdm": 1532879210,
    "yhmc": "zjyw09",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江业务10",
    "yhdm": 1532879211,
    "yhmc": "zjyw10",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王源",
    "yhdm": 1532879239,
    "yhmc": "51112593",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张萌萌",
    "yhdm": 1532879240,
    "yhmc": "51112577",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "李克州",
    "yhdm": 1532879241,
    "yhmc": "51112594",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "郑建祥",
    "yhdm": 1532879243,
    "yhmc": "51078567",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "戴启明",
    "yhdm": 1532879244,
    "yhmc": "51112592",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "许京怡",
    "yhdm": 1532879245,
    "yhmc": "51112595",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "李靖琳",
    "yhdm": 1532879246,
    "yhmc": "51112566",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "赵浦",
    "yhdm": 1532879247,
    "yhmc": "51112596",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "吴霜",
    "yhdm": 1532879248,
    "yhmc": "51112576",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "段顶顶",
    "yhdm": 1532879249,
    "yhmc": "51112574",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王峰湘",
    "yhdm": 1532879250,
    "yhmc": "51078559",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "段杨文",
    "yhdm": 1532879251,
    "yhmc": "51078568",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王平",
    "yhdm": 1532879252,
    "yhmc": "51112571",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "魏建智",
    "yhdm": 1532879253,
    "yhmc": "51112545",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "刘彬彬",
    "yhdm": 1532879254,
    "yhmc": "51112546",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "徐吉庆",
    "yhdm": 1532879255,
    "yhmc": "51078541",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "包婷",
    "yhdm": 1532879256,
    "yhmc": "51112565",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "赵家欢",
    "yhdm": 1532879258,
    "yhmc": "51112543",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张登峰",
    "yhdm": 1532879259,
    "yhmc": "51112573",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "袁涵涵",
    "yhdm": 1532879260,
    "yhmc": "51112569",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "周宝玲",
    "yhdm": 1532879261,
    "yhmc": "51112597",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张晓彤",
    "yhdm": 1532879262,
    "yhmc": "51112568",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "蔡丽丽",
    "yhdm": 1532879263,
    "yhmc": "51112572",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "黄明",
    "yhdm": 1532879265,
    "yhmc": "51078543",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "颜滨华",
    "yhdm": 1532879266,
    "yhmc": "51078586",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "曹蕊",
    "yhdm": 1532879267,
    "yhmc": "51112567",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "姜志杰",
    "yhdm": 1532879268,
    "yhmc": "51078565",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "毛文永",
    "yhdm": 1532879270,
    "yhmc": "51112548",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张广宁",
    "yhdm": 1532879271,
    "yhmc": "51112570",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "叶练",
    "yhdm": 1532879272,
    "yhmc": "51112591",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "唐权周",
    "yhdm": 1532879273,
    "yhmc": "51112544",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "刘俊凤",
    "yhdm": 1532879274,
    "yhmc": "51112590",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江管理员02",
    "yhdm": 1532879279,
    "yhmc": "51112549",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王其伟",
    "yhdm": 1532882203,
    "yhmc": "51112547",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江审批员002",
    "yhdm": 1532882399,
    "yhmc": "51112542",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "产业技改预算编制01",
    "yhdm": 1532882533,
    "yhmc": "zjcyjgysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "产业技改预算审核01",
    "yhdm": 1532882534,
    "yhmc": "zjcyjgyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "产业基建预算编制01",
    "yhdm": 1532882527,
    "yhmc": "zjcyjjysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "产业基建预算审核01",
    "yhdm": 1532882528,
    "yhmc": "zjcyjjyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "电网基建预算编制01",
    "yhdm": 1532882521,
    "yhmc": "zjdwjjysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "电网基建预算审核01",
    "yhdm": 1532882522,
    "yhmc": "zjdwjjyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "电网数字预算编制01",
    "yhdm": 1532882539,
    "yhmc": "zjdwszbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "电网数字预算审核01",
    "yhdm": 1532882540,
    "yhmc": "zjdwszsh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "生产辅助技改预算编制01",
    "yhdm": 1532882529,
    "yhmc": "zjfzjgysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "生产辅助技改预算审核01",
    "yhdm": 1532882530,
    "yhmc": "zjfzjgyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "生产技改预算编制01",
    "yhdm": 1532882523,
    "yhmc": "zjjgysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "生产技改预算审核01",
    "yhdm": 1532882524,
    "yhmc": "zjjgyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "零星购置预算编制01",
    "yhdm": 1532882531,
    "yhmc": "zjlxgzysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "零星购置改预算审核01",
    "yhdm": 1532882532,
    "yhmc": "zjlxgzyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "市场营销预算编制01",
    "yhdm": 1532882535,
    "yhmc": "zjscyxysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "市场营销预算审核01",
    "yhdm": 1532882536,
    "yhmc": "zjscyxyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算01",
    "yhdm": 1532882518,
    "yhmc": "zjtzys01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算02",
    "yhdm": 1532882519,
    "yhmc": "zjtzys02",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江投资预算配置01",
    "yhdm": 1532882520,
    "yhmc": "zjtzyspz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "小型基建预算编制01",
    "yhdm": 1532882525,
    "yhmc": "zjxxjjysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "小型基建预算审核01",
    "yhdm": 1532882526,
    "yhmc": "zjxxjjyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "研究开发预算编制01",
    "yhdm": 1532882537,
    "yhmc": "zjyjkfysbz01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "研究开发预算审核01",
    "yhdm": 1532882538,
    "yhmc": "zjyjkfyssh01",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "sgcctest011",
    "yhdm": 1532882541,
    "yhmc": "sgcctest011",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "sgcctest012",
    "yhdm": 1532882542,
    "yhmc": "sgcctest012",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "sgcctest013",
    "yhdm": 1532882543,
    "yhmc": "sgcctest013",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "李佳晨",
    "yhdm": 1532882544,
    "yhmc": "zj90002575",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "吴秀红",
    "yhdm": 1532882545,
    "yhmc": "zj31175635",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "吴莹",
    "yhdm": 1532882546,
    "yhmc": "zj90000606",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "卢小水",
    "yhdm": 1532882547,
    "yhmc": "zj61112900",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "邵雯",
    "yhdm": 1532882548,
    "yhmc": "zj31175836",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王永华",
    "yhdm": 1532882549,
    "yhmc": "zj61113804",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "吴兆顺",
    "yhdm": 1532882550,
    "yhmc": "zj90002620",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "xnbzcs20",
    "yhdm": 1532882551,
    "yhmc": "xnbzcs20",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算配置01",
    "yhdm": 1532882557,
    "yhmc": "zjpz001",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算配置02",
    "yhdm": 1532882558,
    "yhmc": "zjpz002",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算配置03",
    "yhdm": 1532882559,
    "yhmc": "zjpz003",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算业务01",
    "yhdm": 1532882552,
    "yhmc": "zjyw001",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算业务02",
    "yhdm": 1532882553,
    "yhmc": "zjyw002",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算业务03",
    "yhdm": 1532882554,
    "yhmc": "zjyw003",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算业务04",
    "yhdm": 1532882555,
    "yhmc": "zjyw004",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "浙江核算业务05",
    "yhdm": 1532882556,
    "yhmc": "zjyw005",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "郭和川",
    "yhdm": 1532882561,
    "yhmc": "p68501653",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "高翔",
    "yhdm": 1532882562,
    "yhmc": "p35001009",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "严明安",
    "yhdm": 1532882565,
    "yhmc": "p35000594",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张心怡",
    "yhdm": 1532882566,
    "yhmc": "p90001342",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "陈文通",
    "yhdm": 1532882568,
    "yhmc": "p35003442",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "李策策",
    "yhdm": 1532882569,
    "yhmc": "p35000617",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "范旭明",
    "yhdm": 1532882570,
    "yhmc": "p35003409",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "刘成辉",
    "yhdm": 1532882571,
    "yhmc": "liuchenghui",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "邵风珍",
    "yhdm": 1532882573,
    "yhmc": "shaofengzhen",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "朱佳明",
    "yhdm": 1532882574,
    "yhmc": "zj90001924",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "朱立刚",
    "yhdm": 1532882575,
    "yhmc": "zj31175867",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "诸俊杰",
    "yhdm": 1532882576,
    "yhmc": "zj90004765",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "赵金时",
    "yhdm": 1532882577,
    "yhmc": "zj90001896",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "朱冬冬",
    "yhdm": 1532882578,
    "yhmc": "zj31175168",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张俊",
    "yhdm": 1532882579,
    "yhmc": "zj90000648",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张天浪",
    "yhdm": 1532882580,
    "yhmc": "zj90008254",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张天肇",
    "yhdm": 1532882581,
    "yhmc": "zj90002639",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "章轶慧",
    "yhdm": 1532882582,
    "yhmc": "zj31175435",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "业务韩玉",
    "yhdm": 1532882583,
    "yhmc": "ywhy",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "俞永杰",
    "yhdm": 1532882584,
    "yhmc": "zj90008201",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "郁丹琦",
    "yhdm": 1532882585,
    "yhmc": "zj31175738",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "杨士祥",
    "yhdm": 1532882586,
    "yhmc": "zj31170938",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "杨煦",
    "yhdm": 1532882587,
    "yhmc": "zj31175829",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "叶菁",
    "yhdm": 1532882588,
    "yhmc": "zj31173243",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "易路",
    "yhdm": 1532882589,
    "yhmc": "zj61113710",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "许万选",
    "yhdm": 1532882590,
    "yhmc": "zj31175174",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "杨朝阳",
    "yhdm": 1532882591,
    "yhmc": "zj61214108",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "杨勤国",
    "yhdm": 1532882592,
    "yhmc": "zj31170975",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "徐立",
    "yhdm": 1532882593,
    "yhmc": "zj31174119",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "徐薇",
    "yhdm": 1532882594,
    "yhmc": "zj31174848",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "徐颖男",
    "yhdm": 1532882595,
    "yhmc": "zj31175728",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王栎",
    "yhdm": 1532882596,
    "yhmc": "zj90004775",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王明宣",
    "yhdm": 1532882597,
    "yhmc": "zj31175616",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王翔",
    "yhdm": 1532882598,
    "yhmc": "zj31171724",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "田野",
    "yhdm": 1532882599,
    "yhmc": "zj31170489",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "田益平",
    "yhdm": 1532882600,
    "yhmc": "zj31174219",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王浩国",
    "yhdm": 1532882601,
    "yhmc": "zj10208019",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "业务jdy",
    "yhdm": 1532882602,
    "yhmc": "ywjdy",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "蔡小军",
    "yhdm": 1532882603,
    "yhmc": "zj61113569",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "胡兆杰",
    "yhdm": 1532882604,
    "yhmc": "p00181795",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "陈颖",
    "yhdm": 1532882605,
    "yhmc": "p68113855",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "郑浩",
    "yhdm": 1532882606,
    "yhmc": "p65508015",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "徐洲",
    "yhdm": 1532882607,
    "yhmc": "p90006951",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "王存悦",
    "yhdm": 1532882608,
    "yhmc": "p90002760",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "孙超",
    "yhdm": 1532882610,
    "yhmc": "zj31175622",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "黄闻操",
    "yhdm": 1532882611,
    "yhmc": "zj90002609",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "钱成昊",
    "yhdm": 1532882612,
    "yhmc": "zj90004608",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "田思聪",
    "yhdm": 1532882613,
    "yhmc": "zj90004739",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "李宣宸",
    "yhdm": 1532882614,
    "yhmc": "zj90004791",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "应超楠",
    "yhdm": 1532882615,
    "yhmc": "zj90006987",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "鲁仁桃",
    "yhdm": 1532882616,
    "yhmc": "zj90008264",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "汤如红",
    "yhdm": 1532882617,
    "yhmc": "zj31175045",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "田汉霖",
    "yhdm": 1532882618,
    "yhmc": "zj31175864",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "沈坚",
    "yhdm": 1532882619,
    "yhmc": "zj61114897",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "沈亮印",
    "yhdm": 1532882620,
    "yhmc": "zj90001960",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "苏华骏",
    "yhdm": 1532882621,
    "yhmc": "zj90002653",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "潘一帆",
    "yhdm": 1532882622,
    "yhmc": "zj31175870",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "钱俊",
    "yhdm": 1532882623,
    "yhmc": "zj31173242",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "钱滢锋",
    "yhdm": 1532882624,
    "yhmc": "zj31175853",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "任迪江",
    "yhdm": 1532882625,
    "yhmc": "zj61112886",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "鲁光新",
    "yhdm": 1532882626,
    "yhmc": "zj61112907",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "刘征宇",
    "yhdm": 1532882627,
    "yhmc": "zj31171131",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "卢炜",
    "yhdm": 1532882628,
    "yhmc": "zj31175316",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "陆佳伦",
    "yhdm": 1532882629,
    "yhmc": "zj90004781",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "毛琦扬",
    "yhdm": 1532882630,
    "yhmc": "zj90008241",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "孟庆杰",
    "yhdm": 1532882631,
    "yhmc": "zj31172558",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "牟传强",
    "yhdm": 1532882632,
    "yhmc": "zj31175719",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "倪进红",
    "yhdm": 1532882633,
    "yhmc": "zj61114712",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "刘兴",
    "yhdm": 1532882634,
    "yhmc": "zj61115023",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "江铁",
    "yhdm": 1532882635,
    "yhmc": "zj90008281",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "蒋静",
    "yhdm": 1532882636,
    "yhmc": "zj90006997",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "张三",
    "yhdm": 1532882637,
    "yhmc": "mateng",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "金恩莲",
    "yhdm": 1532882638,
    "yhmc": "zj31175593",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "金红儿",
    "yhdm": 1532882639,
    "yhmc": "zj61112891",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "金建华",
    "yhdm": 1532882640,
    "yhmc": "zj31175312",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "金轩昂",
    "yhdm": 1532882641,
    "yhmc": "zj90002669",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "林旭中",
    "yhdm": 1532882642,
    "yhmc": "zj31174496",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "方磊",
    "yhdm": 1532882643,
    "yhmc": "zj31173506",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "方金涛",
    "yhdm": 1532882644,
    "yhmc": "zj90007029",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "傅利平",
    "yhdm": 1532882645,
    "yhmc": "zj31170887",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "葛一帅",
    "yhdm": 1532882646,
    "yhmc": "zj31175291",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "龚鸣飞",
    "yhdm": 1532882647,
    "yhmc": "zj61110930",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "韩宏量",
    "yhdm": 1532882648,
    "yhmc": "zj61114440",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "韩志坤",
    "yhdm": 1532882649,
    "yhmc": "zj31175411",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "黄蒨蒨",
    "yhdm": 1532882650,
    "yhmc": "zj31175192",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "黄一甲",
    "yhdm": 1532882651,
    "yhmc": "zj31175816",
    "__dynamic": 1
  },
  {
    "jcls": "com.ygsoft.gris.basemanage.service.model.operator.OperatorVO",
    "compid": "1500",
    "compname": "国网浙江省电力有限公司",
    "flid": 0,
    "modelState": 1,
    "__dynamicMap": 1,
    "xsmc": "蔡仪民",
    "yhdm": 1532882652,
    "yhmc": "zj31173321",
    "__dynamic": 1
  }
];